name: data515
channels:
  - defaults
dependencies:
  - anyio=4.10.0=py310hca03da5_0
  - appnope=0.1.4=py310hca03da5_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=py310hca03da5_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - babel=2.17.0=py310hca03da5_0
  - beautifulsoup4=4.14.2=py310hca03da5_0
  - bleach=6.3.0=py310hca03da5_0
  - boltons=25.0.0=py310hca03da5_0
  - brotlicffi=1.2.0.0=py310h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2026.01.04=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - comm=0.2.3=py310hca03da5_0
  - conda=26.1.0=py310hca03da5_0
  - conda-content-trust=0.1.3=py310hca03da5_0
  - conda-libmamba-solver=25.11.0=pyhdf14ebd_0
  - conda-package-handling=2.4.0=py310hca03da5_1
  - conda-package-streaming=0.12.0=py310hca03da5_1
  - cpp-expected=1.1.0=h48ca7d4_0
  - cryptography=46.0.3=py310h81b0bee_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py310hca03da5_0
  - exceptiongroup=1.3.0=py310hca03da5_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - fmt=11.2.0=h643473a_0
  - frozendict=2.4.6=py310haa24f5a_0
  - gettext=0.21.0=hbdbcc25_2
  - h11=0.16.0=py310hca03da5_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py310hca03da5_0
  - ipykernel=6.31.0=py310h7eb115d_0
  - ipython=8.30.0=py310hca03da5_0
  - ipython_pygments_lexers=1.1.1=py310hca03da5_0
  - ipywidgets=8.1.7=py310hca03da5_0
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - json5=0.12.1=py310hca03da5_0
  - jsonpatch=1.33=py310hca03da5_1
  - jsonpointer=3.0.0=py310hca03da5_0
  - jsonschema=4.25.0=py310hca03da5_1
  - jsonschema-specifications=2025.9.1=py310hca03da5_0
  - jupyter=1.1.1=py310hca03da5_0
  - jupyter-lsp=2.2.5=py310hca03da5_0
  - jupyter_client=8.6.3=py310hca03da5_1
  - jupyter_console=6.6.3=py310hca03da5_0
  - jupyter_core=5.9.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_1
  - jupyter_server=2.17.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab=4.5.3=py310hca03da5_1
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_0
  - jupyterlab_widgets=3.0.15=py310hca03da5_0
  - libarchive=3.8.2=ha845c4f_0
  - libcurl=8.17.0=h5bd1c32_0
  - libcxx=20.1.8=hd7fd590_1
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libmamba=2.3.2=hcdddc3d_1
  - libmambapy=2.3.2=py310h678a34b_1
  - libnghttp2=1.67.1=h8189af8_0
  - libsodium=1.0.20=h897f8a9_0
  - libsolv=0.7.30=ha443353_2
  - libssh2=1.11.1=h3e2b118_0
  - libunistring=1.3=h1799b2a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib-inline=0.2.1=py310hca03da5_0
  - menuinst=2.4.2=py310hca03da5_1
  - mistune=3.1.2=py310hca03da5_0
  - msgpack-python=1.1.1=py310h313beb8_0
  - nbclient=0.10.2=py310hca03da5_0
  - nbconvert=7.16.6=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbconvert-pandoc=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - nlohmann_json=3.11.2=h313beb8_0
  - notebook=7.5.0=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_0
  - openssl=3.0.19=ha0b305a_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.5=py310hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py310hca03da5_1
  - pip=23.0.1=py310hca03da5_0
  - platformdirs=4.5.0=py310hca03da5_0
  - pluggy=1.5.0=py310hca03da5_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py310h80987f9_2
  - pycparser=2.23=py310hca03da5_0
  - pygments=2.19.2=py310hca03da5_0
  - python=3.10.19=hf701271_0
  - python-fastjsonschema=2.21.2=py310hca03da5_0
  - python-json-logger=4.0.0=py310hca03da5_0
  - python.app=3=py310h1a28f6b_0
  - pyyaml=6.0.3=py310h091b9d3_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - qtconsole=5.7.0=py310hca03da5_0
  - qtpy=2.4.3=py310hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.5=py310hca03da5_1
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.28.0=py310h931abed_0
  - ruamel.yaml=0.18.16=py310h091b9d3_0
  - ruamel.yaml.clib=0.2.14=py310h091b9d3_0
  - send2trash=1.8.2=py310hca03da5_1
  - setuptools=65.6.3=py310hca03da5_0
  - simdjson=3.10.1=h48ca7d4_0
  - six=1.17.0=py310hca03da5_0
  - sniffio=1.3.1=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py310hca03da5_0
  - terminado=0.18.1=py310hca03da5_0
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py310hca03da5_0
  - tornado=6.5.4=py310haa24f5a_0
  - tqdm=4.67.1=py310h7eb115d_1
  - traitlets=5.14.3=py310hca03da5_0
  - truststore=0.10.1=py310hca03da5_1
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - urllib3=2.6.1=py310hca03da5_0
  - wcwidth=0.2.13=py310hca03da5_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - wheel=0.38.4=py310hca03da5_0
  - widgetsnbextension=4.0.14=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.24.0=py310hbc14757_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - altair==6.0.0
      - arrow==1.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - click==8.3.1
      - dash==4.0.0
      - dash-bootstrap-components==2.0.4
      - fastcore==1.12.16
      - flask==3.1.3
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - importlib-metadata==8.7.1
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - kroger-api==0.2.0
      - lark==1.3.1
      - narwhals==2.17.0
      - numpy==1.25.0
      - pandas==2.0.2
      - pillow==12.1.1
      - plotly==6.5.2
      - protobuf==6.33.5
      - pyarrow==23.0.1
      - pydeck==0.9.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.2.1
      - pytz==2023.3
      - retrying==1.4.2
      - rfc3987-syntax==1.1.0
      - smmap==5.0.2
      - stqdm==0.0.5
      - streamlit==1.54.0
      - streamlit-jupyter==0.3.1
      - tabulate==0.9.0
      - tenacity==9.1.4
      - toml==0.10.2
      - tzdata==2023.3
      - uri-template==1.3.0
      - webcolors==25.10.0
      - werkzeug==3.1.6
      - zipp==3.23.0
prefix: /Users/jiannawong/miniconda3/envs/data515
