name: data515
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - ipykernel
  - requests
  - beautifulsoup4
  - tqdm
  - pyarrow

  - pip
  - pip:
      - streamlit
      - dash
      - dash-bootstrap-components
      - plotly
      - altair
      - kroger-api
      - python-dotenv