name: data515
channels:
  - defaults
dependencies:
  - anyio=4.10.0
  - appnope=0.1.4
  - archspec=0.2.5
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.3.0
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - conda=26.1.0
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - gettext=0.21.0
  - h11=0.16.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.11
  - ipykernel=6.31.0
  - ipython=8.30.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - libarchive=3.8.2
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libiconv=1.16
  - libidn2=2.3.8
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libnghttp2=1.67.1
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libunistring=1.3
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - menuinst=2.4.2
  - mistune=3.1.2
  - msgpack-python=1.1.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - openssl=3.0.19
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=23.0.1
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pygments=2.19.2
  - python=3.10.19
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - python.app=3
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - readline=8.3
  - referencing=0.37.0
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - send2trash=1.8.2
  - setuptools=65.6.3
  - simdjson=3.10.1
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.51.1
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.6.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.14
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - altair==6.0.0
      - arrow==1.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - click==8.3.1
      - dash==4.0.0
      - dash-bootstrap-components==2.0.4
      - fastcore==1.12.16
      - flask==3.1.3
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - importlib-metadata==8.7.1
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - kroger-api==0.2.0
      - lark==1.3.1
      - narwhals==2.17.0
      - numpy==1.25.0
      - pandas==2.0.2
      - pillow==12.1.1
      - plotly==6.5.2
      - protobuf==6.33.5
      - pyarrow==23.0.1
      - pydeck==0.9.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.2.1
      - pytz==2023.3
      - retrying==1.4.2
      - rfc3987-syntax==1.1.0
      - smmap==5.0.2
      - stqdm==0.0.5
      - streamlit==1.54.0
      - streamlit-jupyter==0.3.1
      - tabulate==0.9.0
      - tenacity==9.1.4
      - toml==0.10.2
      - tzdata==2023.3
      - uri-template==1.3.0
      - webcolors==25.10.0
      - werkzeug==3.1.6
      - zipp==3.23.0
prefix: /Users/jiannawong/miniconda3/envs/data515
